In [1]:
# Импорт библиотеки NumPy с общепринятым сокращением
import numpy as np

print("=== 1. СОЗДАНИЕ МАССИВОВ ===\n")

# Создание массива из обычного списка
print("1.1 Массив из списка:")
list_array = np.array([1, 2, 3, 4, 5])
print(f"list_array = {list_array}")

# Создание двумерного массива из списка списков
print("\n1.2 Двумерный массив из списка:")
matrix_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"matrix_2d = \n{matrix_2d}")

# Создание массива из нулей
print("\n1.3 Массив из нулей:")
zeros_array = np.zeros(5)
print(f"zeros_array = {zeros_array}")

# Создание массива из единиц
print("\n1.4 Массив из единиц:")
ones_array = np.ones((3, 3))  # 3x3 матрица из единиц
print(f"ones_array = \n{ones_array}")

# Создание массива с помощью arange
print("\n1.5 Массив с помощью arange:")
range_array = np.arange(0, 10, 2)  # от 0 до 10 с шагом 2
print(f"range_array = {range_array}")

print("\n=== 2. АТРИБУТЫ МАССИВОВ ===\n")

# Демонстрация атрибутов массива
print("Атрибуты matrix_2d:")
print(f"Shape (форма): {matrix_2d.shape}")
print(f"dtype (тип данных): {matrix_2d.dtype}")
print(f"Size (размер): {matrix_2d.size}")
print(f"ndim (количество измерений): {matrix_2d.ndim}")

print("\n=== 3. ИНДЕКСИРОВАНИЕ И СРЕЗЫ ===\n")

# Получение отдельного элемента
print("3.1 Получение отдельных элементов:")
print(f"matrix_2d[0, 1] = {matrix_2d[0, 1]}")  # элемент в строке 0, столбце 1
print(f"matrix_2d[2, 2] = {matrix_2d[2, 2]}")  # элемент в строке 2, столбце 2

# Извлечение подмассива с помощью среза
print("\n3.2 Извлечение подмассивов:")
print(f"matrix_2d[0:2, 1:3] = \n{matrix_2d[0:2, 1:3]}")  # строки 0-1, столбцы 1-2
print(f"matrix_2d[:, 1] = {matrix_2d[:, 1]}")  # все строки, столбец 1
print(f"matrix_2d[1, :] = {matrix_2d[1, :]}")  # строка 1, все столбцы

print("\n=== 4. ВЕКТОРНЫЕ ОПЕРАЦИИ И СТАТИСТИКА ===\n")

# Поэлементное сложение массивов
print("4.1 Поэлементные операции:")
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])

print(f"array1 = {array1}")
print(f"array2 = {array2}")
print(f"array1 + array2 = {array1 + array2}")
print(f"array1 * array2 = {array1 * array2}")
print(f"array2 - array1 = {array2 - array1}")

# Базовые статистические операции
print("\n4.2 Статистические операции:")
data_array = np.array([2, 4, 6, 8, 10, 12])
print(f"data_array = {data_array}")
print(f"Среднее значение: {np.mean(data_array)}")
print(f"Сумма элементов: {np.sum(data_array)}")
print(f"Минимальное значение: {np.min(data_array)}")
print(f"Максимальное значение: {np.max(data_array)}")
print(f"Стандартное отклонение: {np.std(data_array):.2f}")

# Статистика для двумерного массива
print("\n4.3 Статистика для двумерного массива:")
print(f"matrix_2d = \n{matrix_2d}")
print(f"Среднее по всем элементам: {np.mean(matrix_2d)}")
print(f"Среднее по столбцам: {np.mean(matrix_2d, axis=0)}")  # axis=0 - по столбцам
print(f"Среднее по строкам: {np.mean(matrix_2d, axis=1)}")   # axis=1 - по строкам

print("\n=== 5. ДОПОЛНИТЕЛЬНЫЕ ПРИМЕРЫ ===\n")

# Создание массива случайных чисел
print("5.1 Массив случайных чисел:")
random_array = np.random.rand(2, 4)  # 2x4 массив случайных чисел от 0 до 1
print(f"random_array = \n{random_array}")

# Изменение формы массива
print("\n5.2 Изменение формы массива:")
original = np.arange(12)
reshaped = original.reshape(3, 4)
print(f"Исходный массив: {original}")
print(f"После reshape(3, 4): \n{reshaped}")

print("\n=== ВЫПОЛНЕНИЕ ЗАВЕРШЕНО ===")

=== 1. СОЗДАНИЕ МАССИВОВ ===

1.1 Массив из списка:
list_array = [1 2 3 4 5]

1.2 Двумерный массив из списка:
matrix_2d = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

1.3 Массив из нулей:
zeros_array = [0. 0. 0. 0. 0.]

1.4 Массив из единиц:
ones_array = 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

1.5 Массив с помощью arange:
range_array = [0 2 4 6 8]

=== 2. АТРИБУТЫ МАССИВОВ ===

Атрибуты matrix_2d:
Shape (форма): (3, 3)
dtype (тип данных): int64
Size (размер): 9
ndim (количество измерений): 2

=== 3. ИНДЕКСИРОВАНИЕ И СРЕЗЫ ===

3.1 Получение отдельных элементов:
matrix_2d[0, 1] = 2
matrix_2d[2, 2] = 9

3.2 Извлечение подмассивов:
matrix_2d[0:2, 1:3] = 
[[2 3]
 [5 6]]
matrix_2d[:, 1] = [2 5 8]
matrix_2d[1, :] = [4 5 6]

=== 4. ВЕКТОРНЫЕ ОПЕРАЦИИ И СТАТИСТИКА ===

4.1 Поэлементные операции:
array1 = [1 2 3 4]
array2 = [5 6 7 8]
array1 + array2 = [ 6  8 10 12]
array1 * array2 = [ 5 12 21 32]
array2 - array1 = [4 4 4 4]

4.2 Статистические операции:
data_array = [ 2  4  6  8 10 12]
Среднее значение: 7.0
Су